# base configuration

version: '2.1'
services:
  base-eureka:
    command: []



    environment:
    - EUREKA_CLIENT_FETCHREGISTRY=${EUREKA_CLIENT_FETCHREGISTRY:-true}
    - EUREKA_CLIENT_REGISTERWITHEUREKA=${EUREKA_CLIENT_REGISTERWITHEUREKA:-true}
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://user:user_pass@eureka-peer1.local:8761/eureka/}
    - EUREKA_INSTANCE_HOSTNAME=${INSTANCE_NAME:-eureka-peer1}.${INSTANCE_DOMAIN:-local}
    - EUREKA_INSTANCE_IPADDRESS=${HOST_IPADDRESS:-127.0.0.1}
    - EUREKA_INSTANCE_NONSECUREPORT=${SERVER_PORT:-8761}
    - EUREKA_INSTANCE_PREFERIPADDRESS=${EUREKA_INSTANCE_PREFERIPADDRESS:-false}
    - EUREKA_INSTANCE_REGISTRY_DEFAULTOPENFORTRAFFICCOUNT=${EUREKA_INSTANCE_REGISTRY_DEFAULTOPENFORTRAFFICCOUNT:-0}
    - INSTANCE_NAME=${INSTANCE_NAME:-eureka-peer1}
    - LOGGING_LEVEL_=${LOGGING_LEVEL_:-INFO}
    - SECURITY_BASIC_ENABLED=${SECURITY_BASIC_ENABLED:-true}
    - SECURITY_USER_NAME=${SECURITY_USER_NAME:-user}
    - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD:-user_pass}
    - SERVER_PORT=${SERVER_PORT:-8761}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-eureka-cluster}
    #- SPRING_CLOUD_CLIENT_HOSTNAME=${HOST_IPADDRESS:} # profile: manual_ip_hostname
    #- SPRING_CLOUD_CLIENT_IPADDRESS=${HOST_IPADDRESS:} # profile: manual_ip_hostname
    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-development.env,port_nonsecure,peer_awareness}
    image: ${IMAGE_PREFIX:-cloudready}/spring-cloud-eureka-server:${IMAGE_VERSION:-0.0.2-SNAPSHOT}
    restart: always
    volumes:
    - data:/root/.data
    - data:/tmp
