
version: '2.1'
services:
  eureka:
    image: ${DOCKER_REGISTRY:-cloudready}/spring-cloud-eureka-server:0.0.1-SNAPSHOT
    restart: always
    command: []
    container_name: ${INSTANCE_HOSTNAME}
    hostname: ${INSTANCE_HOSTNAME}
    network_mode: host




    ports:
    - "${SERVER_PORT:-8761}:8761"
    volumes:
    - volume-eureka:/root/.data
    - volume-eureka:/tmp
    environment:
    - EUREKA_CLIENT_FETCHREGISTRY=${EUREKA_CLIENT_FETCHREGISTRY:-true}
    - EUREKA_CLIENT_REGISTERWITHEUREKA=${EUREKA_CLIENT_REGISTERWITHEUREKA:-true}
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    - EUREKA_INSTANCE_HOSTNAME=${HOST_IP_ADDRESS}
    - EUREKA_INSTANCE_IP_ADDRESS=${HOST_IP_ADDRESS}
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:-false}
    - EUREKA_INSTANCE_REGISTRY_DEFAULTOPENFORTRAFFICCOUNT=${EUREKA_INSTANCE_REGISTRY_DEFAULTOPENFORTRAFFICCOUNT:-0}
    - EUREKA_INSTANCE_NONSECUREPORT=${SERVER_PORT}
    - LOGGING_LEVEL_=${LOGGING_LEVEL_:-INFO}
    - PEER=${PEER}
    - SECURITY_BASIC_ENABLED=${SECURITY_BASIC_ENABLED:-true}
    - SECURITY_USER_NAME=${SECURITY_USER_NAME:-user}
    - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD:-user_pass}
    - SERVER_PORT=${SERVER_PORT}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
    - SPRING_CLOUD_CLIENT_HOSTNAME=${HOST_IP_ADDRESS}
    - SPRING_CLOUD_CLIENT_IP_ADDRESS=${HOST_IP_ADDRESS}
    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

volumes:
  volume-eureka: {}
