
endpoints:
  env.sensitive: ${ENDPOINTS_ENV_SENSITIVE:true}
  health.sensitive: ${ENDPOINTS_HEALTH_SENSITIVE:false}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://user:user_pass@eureka-standalone.local:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ipAddress:${spring.cloud.client.hostname:${random.int}}}}}:${SERVER_PORT:5678}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFERIPADDRESS:true}

logging:
  #file: ${LOG_FILE:${INSTANCE_NAME:${spring.cloud.client.hostname:${spring.application.name}-${server.port}}}}.log
  #path: ${LOG_PATH:${user.dir}/data/logs/${spring.application.name}}
  level:
    jndi: ${LOGGING_LEVEL_:INFO}
    org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter: ${ENDPOINT_LOGGING_LEVEL_:WARN}
    org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping: ${ENDPOINT_LOGGING_LEVEL_:WARN}
    org.springframework.boot.web.servlet.FilterRegistrationBean: ${ENDPOINT_LOGGING_LEVEL_:WARN}
    org.springframework.boot.web.servlet.ServletRegistrationBean: ${ENDPOINT_LOGGING_LEVEL_:WARN}
    org.springframework.core.type.classreading.AnnotationAttributesReadingVisitor: INFO
    org.springframework.jmx.export.annotation.AnnotationMBeanExporter: ${ENDPOINT_LOGGING_LEVEL_:WARN}
    org.springframework.jndi: ${LOGGING_LEVEL_:INFO}
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: ${ENDPOINT_LOGGING_LEVEL_:WARN}
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: ${ENDPOINT_LOGGING_LEVEL_:WARN}
logging.level.: ${LOGGING_LEVEL_:INFO}

management:
  #context-path: do not set management.context-path on sidecar
  security:
    enabled: true
    roles: SUPERUSER
    sessions: stateless

security:
  basic:
    enabled: false
  sessions: stateless
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:${random.uuid}}
    role: ADMIN

server:
  #context-path: do not set server.context-path on sidecar
  port: ${SERVER_PORT:5678}

sidecar:
  health-uri: http://${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ipAddress:${spring.cloud.client.hostname:localhost}}}}:${SIDECAR_PORT:8761}${SIDECAR_HEALTHURI:/health} # mandatory
  home-page-uri: http://${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ipAddress:${spring.cloud.client.hostname:localhost}}}}:${SIDECAR_PORT:8761}${SIDECAR_HOMEPAGEURI:/} # optional
  hostname: ${SIDECAR_HOSTNAME:${SIDECAR_IPADDRESS:${spring.cloud.client.ipAddress:${spring.cloud.client.hostname:}}}} # optional
  ip-address: ${SIDECAR_IPADDRESS:${spring.cloud.client.ipAddress:}} # optional
  # sidecar.port is the port on which the non-JVM application listens
  port: ${SIDECAR_PORT:8761} # mandatory

spring:
  application.name: ${SPRING_APPLICATION_NAME:the-name-of-non-JVM-application-or-service}
  cloud:
    inetutils:
      preferred-networks:
      - ^192\.168
      - ^10\.
      - ^172\.
      ignored-interfaces:
      - docker0
      - eno.*
      - tun.*
      - utun.*
      - veth.*
      - virbr.*
