
version: '2.1'
services:
  consul-standalone:
    extends:
      file: docker-compose-base.yml
      service: base-consul-agent
    command: ${COMMAND:-agent -dev -client 0.0.0.0}
    container_name: ${INSTANCE_NAME:-consul}.${INSTANCE_DOMAIN:-internal}
    environment:
      CONSUL_BIND_INTERFACE: ${CONSUL_BIND_INTERFACE:-eth0}
    hostname: ${INSTANCE_NAME:-consul}.${INSTANCE_DOMAIN:-internal}
    network_mode: bridge
    privileged: true
    volumes:
    - data:/consul/data

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
