
version: '2.1'
services:
  base-consul-agent:
    image: consul:${IMAGE_VERSION:-1.1.0}
    environment:
      CONSUL_ALLOW_PRIVILEGED_PORTS:
      CONSUL_BIND_INTERFACE: ${CONSUL_BIND_INTERFACE:-eth0}
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    ports:
    # Server RPC is used for communication between Consul clients and servers
    # for internal request forwarding.
    - "${CONSUL_RPC_PORT:-8300}:8300/tcp"
    # Serf LAN and WAN (WAN is used only by Consul servers) are used for gossip between Consul agents.
    # LAN is within the datacenter
    #- "${CONSUL_LAN_GOSSIP_PORT:-8301}:8301/tcp"
    # WAN is between just the Consul servers in all datacenters.
    #- "${CONSUL_LAN_GOSSIP_PORT:-8301}:8301/udp"
    - "${CONSUL_WAN_GOSSIP_PORT:-8302}:8302/tcp"
    - "${CONSUL_WAN_GOSSIP_PORT:-8302}:8302/udp"
    # HTTP and DNS (both TCP and UDP) are the primary interfaces that applications
    # use to interact with Consul.
    - "${CONSUL_HTTP_API_PORT:-8500}:8500/tcp"
    - "${CONSUL_DNS_PORT:-8600}:8600/tcp"
    - "${CONSUL_DNS_PORT:-8600}:8600/udp"
    privileged: true
    restart: always
