
version: '2.1'
services:
  consul-agent-develop:
    extends:
      file: docker-compose-base.yml
      service: base-consul-agent
    command: ${COMMAND:-agent -dev -client 0.0.0.0}
    container_name: ${INSTANCE_NAME:-consul}.${INSTANCE_DOMAIN:-local}
    environment:
      CONSUL_BIND_INTERFACE: ${CONSUL_BIND_INTERFACE:-eth0}
    hostname: ${INSTANCE_NAME:-consul}.${INSTANCE_DOMAIN:-local}
    networks:
      local-network:
        ipv4_address: 172.16.238.15
        ipv6_address: 2001:3984:3989::15
    privileged: true
    volumes:
    - data:/consul/data

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      - subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
