# production development configuration

version: '2.1'
services:
  eureka-sidecar:
    extends:
      file: docker-compose-base.yml
      service: base-eureka-sidecar
    container_name: ${INSTANCE_NAME:-eureka-sidecar}.${INSTANCE_DOMAIN:-internal}
    environment:
    - EUREKA_INSTANCE_PREFERIPADDRESS=${EUREKA_INSTANCE_PREFERIPADDRESS:-true}
    - LOGGING_LEVEL_=${LOGGING_LEVEL_:-INFO}
    - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD:-}
    - SERVER_PORT=${SERVER_PORT:-5678}
    - SIDECAR_HEALTHURI=${SIDECAR_HEALTHURI:-/health}
    - SIDECAR_HOSTNAME=${INSTANCE_NAME:-eureka-sidecar}.${INSTANCE_DOMAIN:-internal} # Optional, for instance-id
    - SIDECAR_IPADDRESS=${SIDECAR_IPADDRESS} # Optional, for instance-id
    - SIDECAR_PORT=${SIDECAR_PORT:-5678}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-the-name-of-non-JVM-application-or-service}
    hostname: ${INSTANCE_NAME:-eureka-sidecar}.${INSTANCE_DOMAIN:-internal}
    network_mode: bridge
    ports:
    - "${SERVER_PORT:-5678}:${SERVER_PORT:-5678}"
    volumes:
    - data:/root/data
    - data:/tmp

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
